#include <tinyvm/runtime_provider.h>

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static bool authorized(const char *path,const TinyvmImport *x){if(!path)return false;FILE *f=fopen(path,"r");if(!f)return false;char expected[512],line[512];snprintf(expected,sizeof expected,"allow %s %s %s %s %s %s",x->library,x->symbol,x->convention,x->effect,x->parameters,x->result);bool found=false;while(fgets(line,sizeof line,f)){line[strcspn(line,"\r\n")]=0;if(strcmp(line,expected)==0){found=true;break;}}fclose(f);return found;}
static const TinyvmString *string_by_id(const TinyvmArtifactV2 *a,uint64_t id){for(size_t i=0;i<a->string_count;++i)if(a->strings[i].id==id)return &a->strings[i];return NULL;}
static const char *string_argument(const TinyvmArtifactV2 *a,const TinyvmRuntimeProvider *provider,uint64_t handle,char **owned){const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);if(tag==1){const TinyvmString *value=string_by_id(a,id);if(!value)return NULL;*owned=malloc(value->length+1);if(!*owned)return NULL;memcpy(*owned,value->bytes,value->length);(*owned)[value->length]=0;return *owned;}if(tag==3&&id<provider->argument_count)return provider->arguments[id];return NULL;}
bool tinyvm_runtime_provider_resolve(void *user,const TinyvmArtifactV2 *a,const TinyvmImport *x,const TinyvmValue *args,size_t count,TinyvmValue *out,const char **fault){TinyvmRuntimeProvider *provider=user;if(!provider||!authorized(provider->policy_path,x)){*fault="active policy does not authorize exact import tuple";return false;}if(strcmp(x->contract,"libc")||strcmp(x->library,"libc.so.6")||strcmp(x->convention,"c")||strcmp(x->effect,"pure")){*fault="runtime provider does not admit import authority";return false;}void *library=dlopen(x->library,RTLD_NOW|RTLD_LOCAL);if(!library){*fault="authorized runtime library is unavailable";return false;}bool ok=false;if(!strcmp(x->symbol,"abs")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,"abs");if(function){const int value=function((int32_t)args[0].bits);*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)value,true};ok=true;}}else if(!strcmp(x->symbol,"strlen")&&!strcmp(x->parameters,"c_string")&&!strcmp(x->result,"c_size_t")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){size_t (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"strlen");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I64,function(value),true};ok=true;}free(owned);}if(!ok)*fault="no exact typed runtime thunk for import";dlclose(library);return ok;}
