#!/usr/bin/env bash
set -euo pipefail
package=flow-selection; version=0.1.0; source_sha=2f7ccd66dd5e21ad884c1b524988db6386badc431f2e2f26fd6ee12b3a28657c; input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage; evidence=/flow/evidence/$package-$version; store=/flow/store; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
die(){ echo "FLOWPKG_FLOW_SELECTION_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; /usr/local/sbin/flowpkg-flow-terminal verify; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build(){ builder; printf '%s  %s\n' "$source_sha" "$input/$package-$version.tar.xz"|sha256sum -c -; rm -rf "$build/source" "$stage"; mkdir "$build/source" "$stage"; tar -xf "$input/$package-$version.tar.xz" -C "$build/source" --strip-components=1; cd "$build/source"; install -d "$stage/usr/bin" "$stage/usr/libexec/flowselection" "$stage/usr/share/doc/$package-$version" "$stage/etc/flowcore/selection"; gcc -std=c17 -D_DEFAULT_SOURCE -O2 -I/usr/include/flowcore flowselect-native.c -L/usr/lib -lflowterminal -o "$stage/usr/libexec/flowselection/flowselect-native"; install -m0755 flowselect flowselection-provider "$stage/usr/bin/"; install -m0755 flowselect-fzf "$stage/usr/libexec/flowselection/"; install -m0644 policy/native/provider "$stage/etc/flowcore/selection/provider"; install -m0644 flowselect-native.c "$stage/usr/share/doc/$package-$version/"; FLOW_SELECTION_POLICY_ROOT="$stage/etc/flowcore/selection" "$stage/usr/bin/flowselect" alpha beta >/dev/null 2>"$evidence/no-implicit-host-provider.log"&&die 'staged dispatcher escaped projection'; grep -Fq 'SHELL=/bin/false' flowselect-fzf; echo 'FLOWPKG_FLOW_SELECTION_BUILD_PASS policy=explicit owner_state=separate'; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\nprotocol=flowselection.cli.v1\ndefault_provider=native\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo "FLOWPKG_FLOW_SELECTION_ADMIT_PASS object=$object"; }
project(){ root; object=$(readlink -f "$pointer"); r=$object/root; test ! -e "$projection"; mkdir "$projection"; :>"$projection/links.list"; :>"$projection/dirs.list"; while IFS= read -r -d '' e; do d=${e#"$r"}; test -d "$d"||{ mkdir "$d"; echo "$d">>"$projection/dirs.list"; }; done < <(find "$r" -mindepth 1 -type d -print0|sort -z); while IFS= read -r -d '' e; do d=${e#"$r"}; test ! -e "$d" -a ! -L "$d"||die "collision $d"; ln -s "$e" "$d"; printf '%s\t%s\n' "$d" "$e">>"$projection/links.list"; done < <(find "$r" -mindepth 1 ! -type d -print0|sort -z); echo "$object">"$projection/object"; }
verify(){ root; test "$(cat /etc/flowcore/selection/provider)" = native; if /usr/bin/flowselect --provider invented alpha beta >/dev/null 2>&1; then die unauthorized; fi; ! grep -Eq -- '--preview |--bind |execute|reload|transform' /usr/libexec/flowselection/flowselect-fzf; test "$(flowselection-provider status)" = $'default\tnative'; echo 'FLOWPKG_FLOW_SELECTION_VERIFY_PASS native=default fzf=explicit owner_state=separate'; }
rollback(){ root; while IFS=$'\t' read -r d t; do test -L "$d" -a "$(readlink "$d")" = "$t"||die changed; rm "$d"; done<"$projection/links.list"; tac "$projection/dirs.list"|while read -r d; do rmdir "$d" 2>/dev/null||:; done; mv "$projection" "$projection.rolled-back.$(date +%s)"; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
