#!/usr/bin/env bash
set -euo pipefail
package=flowpkg-projector; version=0.1.0
source_sha=1c79c05150b9cf8c9884a74601aeb19688f089b5e92bfb826dd8ade931473c64
input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage
evidence=/flow/evidence/$package-$version; store=/flow/store; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
die(){ echo "FLOWPKG_PROJECTOR_PACKAGE_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build(){ builder; printf '%s  %s\n' "$source_sha" "$input/$package-$version.tar.xz"|sha256sum -c -; rm -rf "$build/source" "$stage"; mkdir "$build/source" "$stage"; tar -xf "$input/$package-$version.tar.xz" -C "$build/source" --strip-components=1; cd "$build/source"; install -d "$stage/usr/local/sbin" "$stage/usr/share/doc/$package-$version"; gcc -std=c17 -Wall -Wextra -Werror -O2 src/flowpkg_projector.c -o "$stage/usr/local/sbin/flowpkg-projector"; gcc -std=c17 -Wall -Wextra -Werror -DFLOWPKG_PROJECTOR_TESTING -O2 src/flowpkg_projector.c -o "$build/flowpkg-projector-test"; tests/conformance.sh "$build/flowpkg-projector-test" | tee "$evidence/conformance.log"; tests/differential.sh "$build/flowpkg-projector-test" | tee "$evidence/differential.log"; install -m0644 README.md src/flowpkg_projector.c "$stage/usr/share/doc/$package-$version/"; echo FLOWPKG_PROJECTOR_BUILD_PASS; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\ncontract=flowpkg-projector.v0\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo "FLOWPKG_PROJECTOR_ADMIT_PASS object=$object"; }
project(){ root; object=$(readlink -f "$pointer"); r=$object/root; test ! -e "$projection"||die active; mkdir "$projection"; :>"$projection/links.list"; :>"$projection/dirs.list"; for path in /usr/local/sbin/flowpkg-projector /usr/share/doc/$package-$version/README.md /usr/share/doc/$package-$version/flowpkg_projector.c; do test ! -e "$path" -a ! -L "$path"||die "collision $path"; done; test -d /usr/share/doc/$package-$version||{ mkdir /usr/share/doc/$package-$version; echo /usr/share/doc/$package-$version>>"$projection/dirs.list"; }; ln -s "$r/usr/local/sbin/flowpkg-projector" /usr/local/sbin/flowpkg-projector; printf '%s\t%s\n' /usr/local/sbin/flowpkg-projector "$r/usr/local/sbin/flowpkg-projector">>"$projection/links.list"; for f in README.md flowpkg_projector.c; do ln -s "$r/usr/share/doc/$package-$version/$f" "/usr/share/doc/$package-$version/$f"; printf '%s\t%s\n' "/usr/share/doc/$package-$version/$f" "$r/usr/share/doc/$package-$version/$f">>"$projection/links.list"; done; echo "$object">"$projection/object"; echo FLOWPKG_PROJECTOR_PROJECT_PASS; }
verify(){ root; test -x /usr/local/sbin/flowpkg-projector; grep -Fq 'collision preflight' /usr/share/doc/$package-$version/README.md; echo FLOWPKG_PROJECTOR_VERIFY_PASS; }
rollback(){ root; while IFS=$'\t' read -r d t; do test -L "$d" -a "$(readlink "$d")" = "$t"||die changed; done<"$projection/links.list"; while IFS=$'\t' read -r d t; do rm "$d"; done<"$projection/links.list"; tac "$projection/dirs.list"|while read -r d; do rmdir "$d" 2>/dev/null||:; done; mv "$projection" "$projection.rolled-back.$(date +%s)"; echo FLOWPKG_PROJECTOR_ROLLBACK_PASS; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
