#!/usr/bin/env bash
set -euo pipefail
package=flowforge-cargo; version=0.1.0; source_sha=09744f52b7448e5ee68eedb6acc2de2563888c9c7df7a5da4c8a3674d8610638
input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage; evidence=/flow/evidence/$package-$version; store=/flow/store; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
die(){ echo "FLOWPKG_FLOWFORGE_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build_package(){ builder; printf '%s  %s\n' "$source_sha" "$input/$package-$version.tar.xz"|sha256sum -c -; rm -rf "$stage" "$build/source"; mkdir "$stage" "$build/source"; tar -xf "$input/$package-$version.tar.xz" -C "$build/source" --strip-components=1; install -D -m0755 "$build/source/flowforge-cargo-package" "$stage/usr/local/sbin/flowforge-cargo-package"; install -D -m0644 "$build/source/README.md" "$stage/usr/share/doc/$package-$version/README.md"; bash -n "$stage/usr/local/sbin/flowforge-cargo-package"; grep -Fq 'CARGO_NET_OFFLINE=true' "$stage/usr/local/sbin/flowforge-cargo-package"; echo FLOWPKG_FLOWFORGE_BUILD_PASS class=cargo-package-v0; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\nclass=flowforge.cargo-package.v0\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo FLOWPKG_FLOWFORGE_ADMIT_PASS object=$object; }
project(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector project "$object" / "$projection"; }
verify(){ root; test -x /usr/local/sbin/flowforge-cargo-package; grep -Fq flowforge.cargo-package.v0 /usr/share/doc/$package-$version/README.md; echo FLOWPKG_FLOWFORGE_VERIFY_PASS; }
rollback(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector rollback "$object" / "$projection" "$projection.rolled-back.$(date +%s)"; }
case "${1:-}" in prepare)prepare;;build)build_package;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
