#!/usr/bin/env bash
set -euo pipefail
package=fzf; version=0.74.1; source_sha=f24a9e46c2bc44e2691bb7e17ed1db5909a44be9abc31b0779681281d5f32d55; input=/var/tmp/flowpkg-input/fzf-$version; build=/var/lib/flowbuild/fzf-$version; stage=$build/stage; evidence=/flow/evidence/fzf-$version; store=/flow/store; pointer=$store/packages/fzf/$version/object; projection=$store/projections/fzf-$version
die(){ echo "FLOWPKG_FZF_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; /usr/local/sbin/flowpkg-go verify; install -d -m0755 "$store/packages/fzf/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build(){ builder; printf '%s  %s\n' "$source_sha" "$input/fzf-$version-vendored.tar.xz"|sha256sum -c -; rm -rf "$build/source" "$stage"; mkdir "$build/source" "$stage"; tar -xf "$input/fzf-$version-vendored.tar.xz" -C "$build/source" --strip-components=1; cd "$build/source"; GOTOOLCHAIN=local CGO_ENABLED=0 go test -mod=vendor ./src/...|tee "$evidence/tests.log"; mkdir -p "$stage/usr/bin" "$stage/usr/share/doc/fzf-$version"; GOTOOLCHAIN=local CGO_ENABLED=0 go build -mod=vendor -buildvcs=false -trimpath -ldflags '-s -w -X main.version=0.74.1 -X main.revision=eae8d9d2' -o "$stage/usr/bin/fzf" ./; "$stage/usr/bin/fzf" --version|tee "$evidence/version.log"; cp LICENSE go.mod go.sum flow-module-list.txt flow-vendor-provenance.txt "$stage/usr/share/doc/fzf-$version/"; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-fzf-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\ntag_commit=eae8d9d27eaeffc777699c01bf8f8b8c071908c1\nmodules=vendored-go.sum-verified\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo "FLOWPKG_FZF_ADMIT_PASS object=$object"; }
project(){ root; object=$(readlink -f "$pointer"); test ! -e /usr/bin/fzf; mkdir "$projection"; ln -s "$object/root/usr/bin/fzf" /usr/bin/fzf; printf '/usr/bin/fzf\t%s/root/usr/bin/fzf\n' "$object">"$projection/links.list"; echo "$object">"$projection/object"; }
verify(){ root; test "$(fzf --version)" = '0.74.1 (eae8d9d2)'; echo 'FLOWPKG_FZF_VERIFY_PASS source=canonical modules=offline'; }
rollback(){ root; test "$(readlink /usr/bin/fzf)" = "$(readlink -f "$pointer")/root/usr/bin/fzf"; rm /usr/bin/fzf; mv "$projection" "$projection.rolled-back.$(date +%s)"; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
