#!/usr/bin/env bash
set -euo pipefail
package=git; version=2.55.0; source_sha=457fdb04dc8728e007d4688695e6912e6f680727920f2a40bf11eacc17505357
man_sha=a32d432f80df46a14a05d1104c72d5a13fe27e9feba9aa0f017e54131db6b982
html_sha=d1142c4e28b469d297d6df6519653e92a76c952f55202fde17a72a3b03d49437
input_dir=/var/tmp/flowpkg-input/git-$version; archive=$input_dir/git-$version.tar.xz
man_archive=$input_dir/git-manpages-$version.tar.xz; html_archive=$input_dir/git-htmldocs-$version.tar.xz
build_root=/var/lib/flowbuild/git-$version; source_root=$build_root/source; stage_root=$build_root/stage
evidence_root=/flow/evidence/git-$version; store_root=/flow/store
object_pointer=$store_root/packages/git/$version/object; projection=$store_root/projections/git-$version
die(){ printf 'FLOWPKG_GIT_ERROR %s\n' "$*" >&2; exit 1; }; require_root(){ test "$(id -u)" -eq 0 || die "$1 requires root"; }; require_builder(){ test "$(id -un)" = flowbuilder || die "$1 requires flowbuilder"; }

prepare(){ require_root prepare; test -x /usr/bin/curl || die 'curl dependency absent'; install -d -m0755 "$store_root/packages/git/$version" "$store_root/projections"; install -d -o flowbuilder -g flowbuilder -m0750 "$input_dir" "$build_root" "$evidence_root"; printf 'FLOWPKG_GIT_PREPARED\n'; }
build(){
 require_builder build; cd /; printf '%s  %s\n%s  %s\n%s  %s\n' "$source_sha" "$archive" "$man_sha" "$man_archive" "$html_sha" "$html_archive" | sha256sum -c -
 for item in "$archive" "$man_archive" "$html_archive"; do tar -tf "$item" | awk '/^\//{b=1}{n=split($0,a,"/");for(i=1;i<=n;i++)if(a[i]=="..")b=1}END{exit b}' || die "unsafe archive $item"; done
 if test -d "$stage_root"; then chmod -R u+w "$stage_root"; fi; rm -rf "$source_root" "$stage_root"; install -d -m0750 "$source_root" "$stage_root"; tar -xf "$archive" --strip-components=1 -C "$source_root"; cd "$source_root"
 { printf 'package=git\nversion=%s\nsource_sha256=%s\nfeature_constraint=NO_RUST=1\n' "$version" "$source_sha"; printf 'dependency_curl=%s\nbuilder=%s\n' "$(readlink -f /usr/bin/curl)" "$(id)"; } > "$evidence_root/environment.txt"
 ./configure --prefix=/usr --with-gitconfig=/etc/gitconfig --with-python=python3 --with-libpcre2 2>&1 | tee "$evidence_root/configure.log"
 make -j"$(nproc)" NO_RUST=1 2>&1 | tee "$evidence_root/build.log"
 GIT_UNZIP=nonexist make NO_RUST=1 test -k 2>&1 | tee "$evidence_root/test.log"
 make NO_RUST=1 DESTDIR="$stage_root" perllibdir=/usr/lib/perl5/5.44/site_perl install 2>&1 | tee "$evidence_root/install.log"
 install -d -m0755 "$stage_root/usr/share/man" "$stage_root/usr/share/doc/git-$version"; tar -xf "$man_archive" -C "$stage_root/usr/share/man" --no-same-owner --no-overwrite-dir; tar -xf "$html_archive" -C "$stage_root/usr/share/doc/git-$version" --no-same-owner --no-overwrite-dir
 test -x "$stage_root/usr/bin/git" || die 'staged git absent'; "$stage_root/usr/bin/git" --version > "$evidence_root/runtime.txt"; printf 'FLOWPKG_GIT_BUILD_PASS stage=%s\n' "$stage_root"
}
admit(){ require_root admit; test -f "$evidence_root/test.log" -a -x "$stage_root/usr/bin/git" || die 'completed build absent'; test "$(stat -c %U "$stage_root")" = flowbuilder || die 'stage owner mismatch'; chmod 0755 "$stage_root"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage_root" -cf - .|sha256sum|awk '{print $1}'); object=$store_root/objects/sha256-$digest; if test -e "$object"; then test -d "$object/root" -a -f "$object/manifest.tsv" -a -f "$object/derivation.txt" || die 'existing object invalid'; else incoming=$store_root/objects/.incoming-git-$digest-$$; install -d -m0755 "$incoming"; mv "$stage_root" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; cp "$evidence_root/environment.txt" "$incoming/derivation.txt"; printf 'source_sha256=%s\noutput_tree_sha256=%s\n' "$source_sha" "$digest">>"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$object_pointer"; printf '%s\n' "$object">"$evidence_root/admitted-object.txt"; printf 'FLOWPKG_GIT_ADMIT_PASS object=%s\n' "$object"; }
project(){ require_root project; object=$(readlink -f "$object_pointer"); root=$object/root; test -x "$root/usr/bin/git"||die 'object absent'; test ! -e "$projection"||die 'projection active'; while IFS= read -r -d '' e; do d=${e#"$root"}; test ! -e "$d" -a ! -L "$d"||die "collision $d"; done < <(find "$root" -mindepth 1 \! -type d -print0|sort -z); install -d -m0755 "$projection"; :>"$projection/links.list"; :>"$projection/dirs.list"; while IFS= read -r -d '' e; do d=${e#"$root"}; if test ! -d "$d"; then mkdir "$d"; printf '%s\n' "$d">>"$projection/dirs.list"; fi; done < <(find "$root" -mindepth 1 -type d -print0|sort -z); while IFS= read -r -d '' e; do d=${e#"$root"}; ln -s "$e" "$d"; printf '%s\t%s\n' "$d" "$e">>"$projection/links.list"; done < <(find "$root" -mindepth 1 \! -type d -print0|sort -z); printf '%s\n' "$object">"$projection/object"; printf 'FLOWPKG_GIT_PROJECT_PASS object=%s\n' "$object"; }
verify(){ require_root verify; test -d "$projection"||die 'inactive'; su -s /bin/bash flowbuilder -c 'git --version >/dev/null; d=$(mktemp -d); git -C "$d" init -q; git -C "$d" config user.name FlowTest; git -C "$d" config user.email test@invalid; echo ok > "$d/f"; git -C "$d" add f; git -C "$d" commit -qm test; test "$(git -C "$d" rev-list --count HEAD)" = 1; rm -rf "$d"' || die 'ordinary-user local repository test failed'; systemctl is-active --quiet sshd.service||die 'sshd inactive'; printf 'FLOWPKG_GIT_VERIFY_PASS\n'; }
rollback(){ require_root rollback; test -d "$projection"||die 'inactive'; while IFS=$'\t' read -r d t; do test -L "$d"&&test "$(readlink "$d")" = "$t"||die "changed $d"; rm "$d"; done<"$projection/links.list"; tac "$projection/dirs.list"|while IFS= read -r d; do rmdir "$d" 2>/dev/null||:; done; mv "$projection" "$projection.rolled-back.$(date -u +%Y%m%dT%H%M%SZ)"; printf 'FLOWPKG_GIT_ROLLBACK_PASS\n'; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die 'usage: prepare|build|admit|project|verify|rollback';;esac
