#!/usr/bin/env bash
set -euo pipefail
package=flow-selection; version=0.1.1; source_sha=f98f6ea3502268e7ca5703372e05c1ffea09f336f71323ea0215ebeee4b6ac78; input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage; evidence=/flow/evidence/$package-$version; store=/flow/store; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
die(){ echo "FLOWPKG_FLOW_SELECTION_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; /usr/local/sbin/flowpkg-flow-terminal verify; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build(){ builder; printf '%s  %s\n' "$source_sha" "$input/$package-$version.tar.xz"|sha256sum -c -; rm -rf "$build/source" "$stage"; mkdir "$build/source" "$stage"; tar -xf "$input/$package-$version.tar.xz" -C "$build/source" --strip-components=1; cd "$build/source"; install -d "$stage/usr/bin" "$stage/usr/libexec/flowselection" "$stage/usr/share/doc/$package-$version" "$stage/etc/flowcore/selection"; gcc -std=c17 -D_DEFAULT_SOURCE -O2 -I/usr/include/flowcore flowselect-native.c -L/usr/lib -lflowterminal -o "$stage/usr/libexec/flowselection/flowselect-native"; gcc -std=c17 -O2 native_projection_test.c -lutil -o "$build/native-projection-test"; "$build/native-projection-test" "$stage/usr/libexec/flowselection/flowselect-native" | tee "$evidence/native-projection.log"; install -m0755 flowselect flowselection-provider "$stage/usr/bin/"; install -m0755 flowselect-fzf "$stage/usr/libexec/flowselection/"; install -m0644 policy/native/provider "$stage/etc/flowcore/selection/provider"; install -m0644 flowselect-native.c native_projection_test.c "$stage/usr/share/doc/$package-$version/"; FLOW_SELECTION_POLICY_ROOT="$stage/etc/flowcore/selection" "$stage/usr/bin/flowselect" alpha beta >/dev/null 2>"$evidence/no-implicit-host-provider.log"&&die 'staged dispatcher escaped projection'; grep -Fq 'SHELL=/bin/false' flowselect-fzf; echo 'FLOWPKG_FLOW_SELECTION_BUILD_PASS policy=explicit native_projection=full-list owner_state=separate'; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\nprotocol=flowselection.cli.v1\ndefault_provider=native\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo "FLOWPKG_FLOW_SELECTION_ADMIT_PASS object=$object"; }
project(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector project "$object" / "$projection"; }
verify(){ root; test "$(cat /etc/flowcore/selection/provider)" = native; if /usr/bin/flowselect --provider invented alpha beta >/dev/null 2>&1; then die unauthorized; fi; ! grep -Eq -- '--preview |--bind |execute|reload|transform' /usr/libexec/flowselection/flowselect-fzf; test "$(flowselection-provider status)" = $'default\tnative'; grep -Fq 'Select one (Up/Down, Enter; q cancels)' /usr/share/doc/$package-$version/flowselect-native.c; echo 'FLOWPKG_FLOW_SELECTION_VERIFY_PASS native=default native_projection=full-list fzf=explicit owner_state=separate'; }
rollback(){ root; object=$(readlink -f "$pointer"); archive=$projection.rolled-back.$(date +%s); /usr/local/sbin/flowpkg-projector rollback "$object" / "$projection" "$archive"; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
