#!/usr/bin/env bash
set -euo pipefail
package=rust-bootstrap; version=1.97.1; source_sha=88f28fa9af20594179f85d6df67078dfd6fa93e2f6da5e1e9b0ac4997988ca4f
input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage; evidence=/flow/evidence/$package-$version; store=/flow/store; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
die(){ echo "FLOWPKG_RUST_BOOTSTRAP_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build_package(){ builder; archive=$input/rust-$version-x86_64-unknown-linux-gnu.tar.xz; printf '%s  %s\n' "$source_sha" "$archive"|sha256sum -c -; rm -rf "$build/source" "$stage"; mkdir "$build/source" "$stage"; tar -xf "$archive" -C "$build/source" --strip-components=1; "$build/source/install.sh" --prefix=/opt/flow/rust-bootstrap/$version --destdir="$stage" --disable-ldconfig --components=rustc,cargo,rust-std-x86_64-unknown-linux-gnu; "$stage/opt/flow/rust-bootstrap/$version/bin/rustc" --version|tee "$evidence/rustc-version.log"; "$stage/opt/flow/rust-bootstrap/$version/bin/cargo" --version|tee "$evidence/cargo-version.log"; grep -Fq 'rustc 1.97.1' "$evidence/rustc-version.log"; echo FLOWPKG_RUST_BOOTSTRAP_BUILD_PASS assurance=official-channel-manifest; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; printf 'class=official-bootstrap-seed\nchannel_manifest_sha256=03569b1886ceb5c05276b50c8431ab111de944cd6140fe1fa7d821dd8e0f29cf\narchive_sha256=%s\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo FLOWPKG_RUST_BOOTSTRAP_ADMIT_PASS object=$object; }
project(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector project "$object" / "$projection"; }
verify(){ root; /opt/flow/rust-bootstrap/$version/bin/rustc --version|grep -Fq 'rustc 1.97.1'; /opt/flow/rust-bootstrap/$version/bin/cargo --version|grep -Fq 'cargo 1.97.1'; echo FLOWPKG_RUST_BOOTSTRAP_VERIFY_PASS class=bootstrap-seed; }
rollback(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector rollback "$object" / "$projection" "$projection.rolled-back.$(date +%s)"; }
case "${1:-}" in prepare)prepare;;build)build_package;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
