#!/usr/bin/env bash
set -euo pipefail
profile=fabric-floor-v0; state=/flow/store/profile-realizations/$profile; prior=/flow/store/profile-realizations/selection-providers-v1
projector_object=sha256-96ac8e5d6a5c7199222cc1863cf43c90ce5cbdf52f4cbf896b627b65cf86a8c3
go_object=sha256-31c8d748b54d460c4d114fcd9e94e551164cd109cdee52ddfd74bd3b1b503652
fzf_object=sha256-205dea12964e9664feaeb2987c815d15fbf9ace1fad3bd49ccb34708c8eebf7f
selection_object=sha256-ef7c586436891172f0c820fbc507204646e1561d2e908f5797e8c58a7a6c9199
evidence=/flow/evidence/flowpkg-projector-0.1.0
die(){ echo "FLOWPROFILE_FABRIC_FLOOR_ERROR $*" >&2; exit 1; }; test "$(id -u)" -eq 0||die root
preflight(){ test "$(readlink -f /flow/store/packages/flowpkg-projector/0.1.0/object)" = "/flow/store/objects/$projector_object"||die projector-lock; test "$(readlink -f /flow/store/packages/go/1.26.5/object)" = "/flow/store/objects/$go_object"||die go-lock; test "$(readlink -f /flow/store/packages/fzf/0.74.1/object)" = "/flow/store/objects/$fzf_object"||die fzf-lock; test "$(readlink -f /flow/store/packages/flow-selection/0.1.1/object)" = "/flow/store/objects/$selection_object"||die selection-lock; echo FLOWPROFILE_FABRIC_FLOOR_PREFLIGHT_PASS packages=4; }
record(){ local label=$1 start=$2 end=$3; printf '%s\t%s\n' "$label" "$((end-start))" >>"$evidence/go-projection-nanoseconds.tsv"; }
install_bulk_managers(){ install -m0755 /root/flowpkg-go-bulk-guest.sh /usr/local/sbin/flowpkg-go; install -m0755 /root/flowpkg-fzf-bulk-guest.sh /usr/local/sbin/flowpkg-fzf; install -m0755 /root/flowpkg-flow-selection-bulk-guest.sh /usr/local/sbin/flowpkg-flow-selection; }
write_state(){ mkdir -p "$state"; { printf 'flowpkg-projector\t0.1.0\t%s\n' "$projector_object"; printf 'go\t1.26.5\t%s\n' "$go_object"; printf 'fzf\t0.74.1\t%s\n' "$fzf_object"; printf 'flow-selection\t0.1.1\t%s\n' "$selection_object"; } >"$state/active.tsv.incoming"; mv "$state/active.tsv.incoming" "$state/active.tsv"; }
migrate(){ preflight; test -f "$prior/active.tsv"||die prior-profile-inactive; test ! -e /etc/flowcore/selection/provider.local||die owner-state; :>"$evidence/go-projection-nanoseconds.tsv"; /usr/local/sbin/flowpkg-flow-selection rollback; /usr/local/sbin/flowpkg-fzf rollback; start=$(date +%s%N); /usr/local/sbin/flowpkg-go rollback; end=$(date +%s%N); record shell_rollback "$start" "$end"; install_bulk_managers; start=$(date +%s%N); /usr/local/sbin/flowpkg-go project; end=$(date +%s%N); record native_project "$start" "$end"; start=$(date +%s%N); /usr/local/sbin/flowpkg-go rollback; end=$(date +%s%N); record native_rollback "$start" "$end"; start=$(date +%s%N); /usr/local/sbin/flowpkg-go project; end=$(date +%s%N); record native_reproject "$start" "$end"; /usr/local/sbin/flowpkg-fzf project; /usr/local/sbin/flowpkg-flow-selection project; write_state; mv "$prior/active.tsv" "$prior/superseded-by-fabric-floor-v0.tsv"; verify; echo FLOWPROFILE_FABRIC_FLOOR_MIGRATE_PASS; }
activate(){ preflight; test ! -f "$state/active.tsv"||die already-active; /usr/local/sbin/flowpkg-projector-package project; install_bulk_managers; /usr/local/sbin/flowpkg-go project; /usr/local/sbin/flowpkg-fzf project; /usr/local/sbin/flowpkg-flow-selection project; write_state; verify; echo FLOWPROFILE_FABRIC_FLOOR_ACTIVATE_PASS; }
deactivate(){ test ! -e /etc/flowcore/selection/provider.local||die owner-state; /usr/local/sbin/flowpkg-flow-selection rollback; /usr/local/sbin/flowpkg-fzf rollback; /usr/local/sbin/flowpkg-go rollback; /usr/local/sbin/flowpkg-projector-package rollback; mv "$state/active.tsv" "$state/inactive.$(date +%s).tsv"; echo FLOWPROFILE_FABRIC_FLOOR_DEACTIVATE_PASS; }
verify(){ preflight; test -f "$state/active.tsv"; /usr/local/sbin/flowpkg-projector-package verify; /usr/local/sbin/flowpkg-go verify; /usr/local/sbin/flowpkg-fzf verify; /usr/local/sbin/flowpkg-flow-selection verify; systemctl is-active --quiet sshd.service; echo FLOWPROFILE_FABRIC_FLOOR_VERIFY_PASS engine=native packages=4; }
status(){ test -f "$state/active.tsv"&&{ echo active; cat "$state/active.tsv"; }||echo inactive; }
case "${1:-}" in preflight)preflight;;migrate)migrate;;activate)activate;;deactivate)deactivate;;verify)verify;;status)status;;*)die usage;;esac
