#!/usr/bin/env bash
set -euo pipefail
package=sel; version=0.2.1
source_sha=bcd5b0b320b754513e56f1cfec3d90dd4890211dc94ef5bdd0e340a967392c8d
flow_sha=bc671ec27d36ce2d21c476c9ae169d00b7095cdc9d343da52145fdc68c36ac10
assembly_sha=52715cec9debe0233b3cfa331100da22689d2b2854417772d364cba0d3e2562d
archive=/var/tmp/flowpkg-input/$package-$version/$package-$version.tar.xz
build_root=/var/lib/flowbuild/$package-$version; source_root=$build_root/source; stage_root=$build_root/stage
evidence_root=/flow/evidence/$package-$version; store_root=/flow/store
object_pointer=$store_root/packages/$package/$version/object; projection=$store_root/projections/$package-$version
die(){ printf 'FLOWPKG_SEL_V021_ERROR %s\n' "$*" >&2; exit 1; }; require_root(){ test "$(id -u)" -eq 0||die "$1 requires root"; }; require_builder(){ test "$(id -un)" = flowbuilder||die "$1 requires flowbuilder"; }
prepare(){ require_root prepare; ldconfig -p|grep -Fq libflowterminal.so.1||die 'Flow terminal capability absent'; install -d -m0755 "$store_root/objects" "$store_root/packages/$package/$version" "$store_root/projections"; install -d -o flowbuilder -g flowbuilder -m0750 "${archive%/*}" "$build_root" "$evidence_root"; printf 'FLOWPKG_SEL_V021_PREPARED\n'; }
build(){ require_builder build; cd /; printf '%s  %s\n' "$source_sha" "$archive"|sha256sum -c -; tar -tf "$archive"|awk '/^\//{b=1}{n=split($0,a,"/");for(i=1;i<=n;i++)if(a[i]=="..")b=1}END{exit b}'||die 'unsafe archive'; test ! -d "$stage_root"||chmod -R u+w "$stage_root"; rm -rf "$source_root" "$stage_root"; install -d -m0750 "$source_root" "$stage_root/usr/bin" "$stage_root/usr/share/doc/sel-$version"; tar -xf "$archive" -C "$source_root" --strip-components=1; cd "$source_root"; printf '%s  sel.flow\n%s  sel.s\n' "$flow_sha" "$assembly_sha"|sha256sum -c -; grep -Fq 'provider=libflowterminal.so.1' derivation.txt||die 'provider lineage absent'; sed '/^[[:space:]]*\.addrsig/d' sel.s >sel.gas.s; diff -u sel.s sel.gas.s >"$evidence_root/clang-to-gas.patch"||test "$?" -eq 1; test "$(grep -c '^-[[:space:]]*\.addrsig' "$evidence_root/clang-to-gas.patch")" -eq 8||die 'adaptation exceeded .addrsig metadata boundary'; gcc -fPIE -pie -Wl,--build-id=sha1 sel.gas.s -L/usr/lib -lflowterminal -o "$stage_root/usr/bin/sel" 2>&1|tee "$evidence_root/build.log"; cp ./* "$stage_root/usr/share/doc/sel-$version/"; printf q|TERM=invented-terminal "$stage_root/usr/bin/sel" >"$evidence_root/unknown-terminal.log"||test "$?" -eq 1; grep -q 'selection: none' "$evidence_root/unknown-terminal.log"; ! strings "$stage_root/usr/bin/sel"|grep -Eq 'ncurses|terminfo|xterm-kitty'; { printf 'package=sel\nversion=%s\nsource_sha256=%s\nflow_source_sha256=%s\nassembly_sha256=%s\nprovider=libflowterminal.so.1\nadaptation=remove-clang-addrsig-metadata\nbuilder=%s\n' "$version" "$source_sha" "$flow_sha" "$assembly_sha" "$(id)"; gcc --version|sed -n 1p; } >"$evidence_root/environment.txt"; printf 'FLOWPKG_SEL_V02_BUILD_PASS\n'; }
admit(){ require_root admit; test -x "$stage_root/usr/bin/sel" -a -f "$evidence_root/unknown-terminal.log"||die 'completed build absent'; chmod -R a+rX "$stage_root"; chmod 0755 "$stage_root"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage_root" -cf - .|sha256sum|awk '{print $1}'); object=$store_root/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store_root/objects/.incoming-sel-$digest-$$; install -d -m0755 "$incoming"; mv "$stage_root" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; cp "$evidence_root/environment.txt" "$incoming/derivation.txt"; printf 'output_tree_sha256=%s\n' "$digest">>"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$object_pointer"; printf '%s\n' "$object">"$evidence_root/admitted-object.txt"; printf 'FLOWPKG_SEL_V02_ADMIT_PASS object=%s\n' "$object"; }
project(){ require_root project; object=$(readlink -f "$object_pointer"); root=$object/root; test -x "$root/usr/bin/sel"||die 'object absent'; test ! -e "$projection"||die 'projection active'; while IFS= read -r -d '' e; do d=${e#"$root"}; test ! -e "$d" -a ! -L "$d"||die "collision $d"; done < <(find "$root" -mindepth 1 \! -type d -print0|sort -z); install -d -m0755 "$projection"; :>"$projection/links.list"; :>"$projection/dirs.list"; while IFS= read -r -d '' e; do d=${e#"$root"}; if test ! -d "$d"; then mkdir "$d"; printf '%s\n' "$d">>"$projection/dirs.list"; fi; done < <(find "$root" -mindepth 1 -type d -print0|sort -z); while IFS= read -r -d '' e; do d=${e#"$root"}; ln -s "$e" "$d"; printf '%s\t%s\n' "$d" "$e">>"$projection/links.list"; done < <(find "$root" -mindepth 1 \! -type d -print0|sort -z); printf '%s\n' "$object">"$projection/object"; printf 'FLOWPKG_SEL_V02_PROJECT_PASS\n'; }
verify(){ require_root verify; test -d "$projection"||die 'projection inactive'; su -s /bin/bash flowbuilder -c 'printf q|TERM=xterm-kitty /usr/bin/sel >/tmp/sel-kitty.log; test $? -eq 1' || test "$?" -eq 1; grep -q 'selection: none' /tmp/sel-kitty.log; su -s /bin/bash flowbuilder -c 'printf "\033[B\n"|TERM=alacritty /usr/bin/sel >/tmp/sel-alacritty.log'; grep -q 'cursor: beta' /tmp/sel-alacritty.log; grep -q 'selected: beta' /tmp/sel-alacritty.log; su -s /bin/bash flowbuilder -c 'printf "\033[B\033[B\033[A\n"|TERM=invented-terminal /usr/bin/sel >/tmp/sel-invented.log'; grep -q 'selected: beta' /tmp/sel-invented.log; rm -f /tmp/sel-kitty.log /tmp/sel-alacritty.log /tmp/sel-invented.log; systemctl is-active --quiet sshd.service||die 'sshd inactive'; printf 'FLOWPKG_SEL_V021_VERIFY_PASS navigation=up,down,enter projections=kitty,alacritty,unknown terminfo=unused\n'; }
rollback(){ require_root rollback; test -d "$projection"||die 'projection inactive'; while IFS=$'\t' read -r d t; do test -L "$d" -a "$(readlink "$d")" = "$t"||die "changed $d"; rm "$d"; done<"$projection/links.list"; tac "$projection/dirs.list"|while IFS= read -r d; do rmdir "$d" 2>/dev/null||:; done; mv "$projection" "$projection.rolled-back.$(date -u +%Y%m%dT%H%M%SZ)"; printf 'FLOWPKG_SEL_V02_ROLLBACK_PASS\n'; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die 'usage: prepare|build|admit|project|verify|rollback';;esac
