#!/usr/bin/env bash
set -euo pipefail
package=go; version=1.26.5; source_sha=495be4bc87176ac567392e5b4116abd98466d33d7b49d41e764ccc6976b2dc42; bootstrap_sha=bbca37cc395c974ffa4893ee35819ad23ebb27426df87af92e93a9ec66ef8712
input=/var/tmp/flowpkg-input/go-$version; build=/var/lib/flowbuild/go-$version; stage=$build/stage; evidence=/flow/evidence/go-$version; store=/flow/store; pointer=$store/packages/go/$version/object; projection=$store/projections/go-$version
die(){ echo "FLOWPKG_GO_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; install -d -m0755 "$store/objects" "$store/packages/go/$version" "$store/projections"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build(){ builder; cd /; printf '%s  %s\n%s  %s\n' "$source_sha" "$input/go$version.src.tar.gz" "$bootstrap_sha" "$input/go1.24.6.linux-amd64.bootstrap.tar.gz"|sha256sum -c -; rm -rf "$build/bootstrap" "$build/first" "$build/source-bootstrap" "$stage"; mkdir "$build/bootstrap" "$build/first" "$stage"; tar -xf "$input/go1.24.6.linux-amd64.bootstrap.tar.gz" -C "$build/bootstrap" --strip-components=1; tar -xf "$input/go$version.src.tar.gz" -C "$build/first" --strip-components=1; (cd "$build/first/src"; GOROOT_BOOTSTRAP="$build/bootstrap" CGO_ENABLED=1 ./make.bash) >"$evidence/stage1.log" 2>&1; find "$build/first/bin" "$build/first/pkg/tool/linux_amd64" -type f -print0|sort -z|xargs -0 sha256sum|sed "s#$build/first/##">"$evidence/stage1.sha256"; mv "$build/first" "$build/source-bootstrap"; mkdir "$stage/usr"; tar -xf "$input/go$version.src.tar.gz" -C "$stage/usr"; (cd "$stage/usr/go/src"; GOROOT_BOOTSTRAP="$build/source-bootstrap" CGO_ENABLED=1 ./make.bash) >"$evidence/stage2.log" 2>&1; find "$stage/usr/go/bin" "$stage/usr/go/pkg/tool/linux_amd64" -type f -print0|sort -z|xargs -0 sha256sum|sed "s#$stage/usr/go/##">"$evidence/stage2.sha256"; diff -u "$evidence/stage1.sha256" "$evidence/stage2.sha256" >"$evidence/convergence.diff"; mkdir -p "$stage/usr/bin"; ln -s ../lib/go/bin/go "$stage/usr/bin/go"; mkdir -p "$stage/usr/lib"; mv "$stage/usr/go" "$stage/usr/lib/go"; "$stage/usr/lib/go/bin/go" version|tee "$evidence/version.log"; echo 'FLOWPKG_GO_BUILD_PASS convergence=exact tools=10'; }
admit(){ root; test -x "$stage/usr/lib/go/bin/go"; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-go-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\nbootstrap_seed_sha256=%s\nconvergence=exact\noutput_tree_sha256=%s\n' "$source_sha" "$bootstrap_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo "FLOWPKG_GO_ADMIT_PASS object=$object"; }
project(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector project "$object" / "$projection"; }
verify(){ root; test "$(/usr/bin/go version)" = 'go version go1.26.5 linux/amd64'; test ! -s "$evidence/convergence.diff"; echo 'FLOWPKG_GO_VERIFY_PASS source_built=yes convergence=exact'; }
rollback(){ root; object=$(readlink -f "$pointer"); archive=$projection.rolled-back.$(date +%s); /usr/local/sbin/flowpkg-projector rollback "$object" / "$projection" "$archive"; }
case "${1:-}" in prepare)prepare;;build)build;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
