#!/usr/bin/env bash
set -euo pipefail
package=flow-zoxide-integration; version=0.1.0; source_sha=1e0e5e55bf13b15dab9c34f6a47ea44a4eac85baedb44ad3ca06d3b131cf7c92
input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage; evidence=/flow/evidence/$package-$version; store=/flow/store; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
die(){ echo "FLOWPKG_ZOXIDE_INTEGRATION_ERROR $*" >&2; exit 1; }; root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; test -x /usr/bin/zoxide||die zoxide-provider; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build_package(){ builder; printf '%s  %s\n' "$source_sha" "$input/$package-$version.tar.xz"|sha256sum -c -; rm -rf "$build/source" "$stage"; mkdir "$build/source" "$stage"; tar -xf "$input/$package-$version.tar.xz" -C "$build/source" --strip-components=1; install -D -m0755 "$build/source/flow-zoxide-init" "$stage/usr/bin/flow-zoxide-init"; install -D -m0644 "$build/source/README.md" "$stage/usr/share/doc/$package-$version/README.md"; test "$(find "$stage" -type f | wc -l)" -eq 2; ! find "$stage" -path '*/etc/skel/*' -o -name '.bashrc' -o -name '.zshrc' | grep -q .; echo FLOWPKG_ZOXIDE_INTEGRATION_BUILD_PASS policy=owner-opt-in; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; printf 'source_sha256=%s\npolicy=explicit-owner-opt-in\noutput_tree_sha256=%s\n' "$source_sha" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo FLOWPKG_ZOXIDE_INTEGRATION_ADMIT_PASS object=$object; }
project(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector project "$object" / "$projection"; }
verify(){ root; test -x /usr/bin/flow-zoxide-init; /usr/bin/flow-zoxide-init bash|grep -Fq '_ZO_DOCTOR'; /usr/bin/flow-zoxide-init zsh|grep -Fq '_ZO_DOCTOR'; test "$(type -t cd)" = builtin; echo FLOWPKG_ZOXIDE_INTEGRATION_VERIFY_PASS policy=owner-opt-in canonical_cd=preserved; }
rollback(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector rollback "$object" / "$projection" "$projection.rolled-back.$(date +%s)"; }
case "${1:-}" in prepare)prepare;;build)build_package;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die usage;;esac
