#!/usr/bin/env bash
set -u

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
root_build="${FLOWCORE_BUILD_DIR:-${root}/build}"
flowmini_root="${FLOWMINI_ROOT:-${root}/Flowmini/flowmini_v25_symboltable_projection}"
flowmini_build="${FLOWMINI_CTEST_BUILD_DIR:-${root_build}/flowmini}"
out_json="${FLOWMINI_STATUS_JSON:-${root}/reports/flowmini-test-status.json}"
out_md="${FLOWMINI_STATUS_MD:-${root}/reports/flowmini-test-status.md}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT
mkdir -p "$(dirname "${out_json}")" "$(dirname "${out_md}")"

run_capture() {
  local name="$1"; shift
  "$@" >"${tmpdir}/${name}.log" 2>&1
  printf '%s' "$?" >"${tmpdir}/${name}.rc"
}
set +e
run_capture root_ctest ctest --test-dir "${root_build}" --output-on-failure
run_capture flowmini_ctest ctest --test-dir "${flowmini_build}" --output-on-failure
run_capture categorized env FLOWMINI_ROOT="${flowmini_root}" FLOWMINI_BUILD_DIR="${root_build}/flowmini" FLOWMINI_NO_BUILD=1 \
  "${root}/tools/run-flowmini-test-suite.sh"
set -e

python3 - "${tmpdir}" "${out_json}" "${out_md}" "${root_build}" "${flowmini_build}" <<'PY'
import json, re, sys
from pathlib import Path
tmp, out_json, out_md, root_build, flowmini_build = map(Path, sys.argv[1:])

def read(name): return (tmp / f'{name}.log').read_text(errors='replace')
def rc(name): return int((tmp / f'{name}.rc').read_text())
def ctest(name):
    text=read(name)
    m=re.search(r'(\d+)% tests passed, (\d+) tests failed out of (\d+)', text)
    if not m:
        m=re.search(r'(\d+) tests passed, (\d+) tests failed out of (\d+)', text)
    if m:
        passed, failed, total=map(int,m.groups())
        # The first group is a percentage for the normal CTest summary.
        if passed > total: passed = total - failed
        else: passed = total - failed
        return {'total':total,'passed':passed,'failed':failed,'exit_code':rc(name),'status':'pass' if rc(name)==0 and failed==0 else 'fail'}
    return {'total':None,'passed':None,'failed':None,'exit_code':rc(name),'status':'unknown'}
def categorized():
    text=read('categorized')
    vals={k:int(v) for k,v in re.findall(r'^\s*(total|pass|bad):\s+(\d+)', text, re.M)}
    return {'total':vals.get('total'),'passed':vals.get('pass'),'failed':vals.get('bad'),'exit_code':rc('categorized'),'status':'pass' if rc('categorized')==0 and vals.get('bad',1)==0 else 'known-gaps'}
report={'format':'flowmini.test_status','version':1,'root_ctest':ctest('root_ctest'),'focused_flowmini_ctest':ctest('flowmini_ctest'),'categorized_flowmini_suite':categorized(),'commands':{'root_ctest':f'ctest --test-dir {root_build} --output-on-failure','focused_flowmini_ctest':f'ctest --test-dir {flowmini_build} --output-on-failure','categorized':f'FLOWMINI_ROOT={flowmini_build.parent.parent / "Flowmini/flowmini_v25_symboltable_projection"} FLOWMINI_BUILD_DIR={root_build / "flowmini"} tools/run-flowmini-test-suite.sh'}}
Path(out_json).write_text(json.dumps(report,indent=2,sort_keys=True)+'\n')
lines=['# Flowmini test status','', 'Generated by `tools/report-flowmini-test-status.sh`.', '', '| Gate | Total | Passed | Failed | Status |','|---|---:|---:|---:|---|']
for key,label in [('root_ctest','Root CTest'),('focused_flowmini_ctest','Focused Flowmini CTest'),('categorized_flowmini_suite','Categorized Flowmini suite')]:
 d=report[key]; lines.append(f"| {label} | {d['total'] if d['total'] is not None else 'unknown'} | {d['passed'] if d['passed'] is not None else 'unknown'} | {d['failed'] if d['failed'] is not None else 'unknown'} | {d['status']} |")
lines += ['', 'The JSON report is evidence produced from the tests; it does not replace the test commands. Categorized-suite failures are reported as known gaps when the runner exits nonzero.']
Path(out_md).write_text('\n'.join(lines)+'\n')
print(out_json)
PY
