#!/usr/bin/env bash
set -euo pipefail
spec=${1:?spec required}; action=${2:?action required}; store=/flow/store
die(){ echo "FLOWFORGE_CARGO_V02_ERROR $*" >&2; exit 1; }
field(){ local key=$1; awk -F '\t' -v k="$key" '$1==k {sub(/^[^\t]*\t/,""); print; exit}' "$spec"; }
test "$(field format)" = flowforge.cargo-package.v0.2||die format
package=$(field package); version=$(field version); archive=$(field source_archive); source_sha=$(field source_sha256); toolchain=$(field toolchain_prefix); verify_path=$(field verify_path); verify_version=$(field verify_version)
case "$package/$version/$archive" in *[!A-Za-z0-9._/-]*) die invalid-identity;; esac
input=/var/tmp/flowpkg-input/$package-$version; build=/var/lib/flowbuild/$package-$version; stage=$build/stage; evidence=/flow/evidence/$package-$version; pointer=$store/packages/$package/$version/object; projection=$store/projections/$package-$version
root(){ test "$(id -u)" -eq 0||die root; }; builder(){ test "$(id -un)" = flowbuilder||die builder; }
prepare(){ root; test -x "$toolchain/bin/cargo" -a -x /usr/local/sbin/flowpkg-projector||die providers; install -d -m0755 "$store/packages/$package/$version"; install -d -o flowbuilder -g flowbuilder -m0750 "$input" "$build" "$evidence"; }
build_package(){ builder; printf '%s  %s\n' "$source_sha" "$input/$archive"|sha256sum -c -; rm -rf "$build/source" "$stage" "$build/home" "$build/tmp" "$build/cargo-home"; mkdir "$build/source" "$stage" "$build/home" "$build/tmp" "$build/cargo-home"; tar -xf "$input/$archive" -C "$build/source" --strip-components=1; cd "$build/source"; export PATH="$toolchain/bin:/usr/bin:/bin" HOME="$build/home" TMPDIR="$build/tmp" CARGO_HOME="$build/cargo-home" CARGO_NET_OFFLINE=true GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null SOURCE_DATE_EPOCH=0; read -r -a test_words <<<"$(field test_args)"; cargo "${test_words[@]}" 2>&1|tee "$evidence/test.log"; read -r -a build_words <<<"$(field build_args)"; cargo "${build_words[@]}" 2>&1|tee "$evidence/build.log"; while IFS=$'\t' read -r key executable arguments destination mode; do test "$key" != generate||{ case "$executable/$destination" in /*)die generate-path;;*/*) :;;*)die generate-executable;;esac; case "$destination" in /*) :;;*)die generate-destination;;esac; read -r -a words <<<"$arguments"; install -d "$(dirname "$stage$destination")"; "$executable" "${words[@]}" >"$stage$destination"; chmod "$mode" "$stage$destination"; }; done<"$spec"; while IFS=$'\t' read -r key source destination mode; do test "$key" != install||{ case "$destination" in /*) :;;*)die install-path;;esac; install -D -m "$mode" "$source" "$stage$destination"; }; done<"$spec"; install -D -m0644 "$spec" "$stage/usr/share/flowforge/specs/$package-$version.tsv"; "$stage$verify_path" --version|head -1|tee "$evidence/version.log"; test "$(cat "$evidence/version.log")" = "$verify_version"||die version; echo FLOWFORGE_CARGO_V02_BUILD_PASS package=$package version=$version offline=yes isolation=private; }
admit(){ root; chmod -R a+rX "$stage"; digest=$(tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner -C "$stage" -cf - .|sha256sum|awk '{print $1}'); object=$store/objects/sha256-$digest; if test ! -e "$object"; then incoming=$store/objects/.incoming-$package-$digest-$$; mkdir "$incoming"; mv "$stage" "$incoming/root"; chown -R root:root "$incoming/root"; (cd "$incoming/root"&&find . -mindepth 1 -printf '%y\t%m\t%u\t%g\t%p\t%l\n'|LC_ALL=C sort)>"$incoming/manifest.tsv"; printf 'forge=flowforge.cargo-package.v0.2\nsource_sha256=%s\ntoolchain=%s\noffline=true\nisolation=home,tmp,cargo,git\noutput_tree_sha256=%s\n' "$source_sha" "$toolchain" "$digest">"$incoming/derivation.txt"; chmod -R a-w "$incoming"; mv "$incoming" "$object"; fi; ln -sfn "$object" "$pointer"; echo FLOWFORGE_CARGO_V02_ADMIT_PASS object=$object; }
project(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector project "$object" / "$projection"; }
verify(){ root; object=$(readlink -f "$pointer"); test "$(cat "$projection/object")" = "$object"; test "$("$verify_path" --version|head -1)" = "$verify_version"; echo FLOWFORGE_CARGO_V02_VERIFY_PASS package=$package version=$version; }
rollback(){ root; object=$(readlink -f "$pointer"); /usr/local/sbin/flowpkg-projector rollback "$object" / "$projection" "$projection.rolled-back.$(date +%s)"; }
case "$action" in prepare)prepare;;build)build_package;;admit)admit;;project)project;;verify)verify;;rollback)rollback;;*)die action;;esac
